#!/bin/bash
# ═══════════════════════════════════════════════════════════
# FIX-PG-AUTOCONF — Emergency fix for corrupted postgresql.auto.conf
# ═══════════════════════════════════════════════════════════
#
# Fixes the "syntax error in postgresql.auto.conf" crash loop.
#
# Usage:
#   sudo bash fix-pg-autoconf.sh                    # Fix as standalone primary
#   sudo bash fix-pg-autoconf.sh --standby          # Fix as streaming standby
#   sudo bash fix-pg-autoconf.sh --standby --primary-host 178.128.55.28
#
# Run from: The server where PostgreSQL is crash-looping
# ═══════════════════════════════════════════════════════════
set -euo pipefail

# ── Defaults ──
MODE="primary"
PRIMARY_HOST="178.128.55.28"
REPL_USER="replicator"
REPL_PASS="Admin@123"
REPL_SLOT="dr_mumbai"
CONTAINER_NAME="devops-learning-db-dr"

# ── Parse args ──
while [[ $# -gt 0 ]]; do
  case $1 in
    --standby)       MODE="standby"; shift ;;
    --primary-host)  PRIMARY_HOST="$2"; shift 2 ;;
    --repl-user)     REPL_USER="$2"; shift 2 ;;
    --repl-pass)     REPL_PASS="$2"; shift 2 ;;
    --repl-slot)     REPL_SLOT="$2"; shift 2 ;;
    --container)     CONTAINER_NAME="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: sudo bash fix-pg-autoconf.sh [--standby] [--primary-host HOST]"
      echo ""
      echo "Options:"
      echo "  --standby           Configure as streaming standby (default: primary)"
      echo "  --primary-host HOST Primary server IP (default: 178.128.55.28)"
      echo "  --repl-user USER    Replication user (default: replicator)"
      echo "  --repl-pass PASS    Replication password (default: Admin@123)"
      echo "  --repl-slot SLOT    Replication slot name (default: dr_mumbai)"
      echo "  --container NAME    Docker container name (default: devops-learning-db-dr)"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo "═══════════════════════════════════════════════"
echo "  FIX-PG-AUTOCONF — Emergency Repair"
echo "═══════════════════════════════════════════════"
echo "  Mode:      $MODE"
echo "  Container: $CONTAINER_NAME"
echo "  Time:      $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

# ── Step 1: Find PG data directory ──
echo "1/5 — Finding PostgreSQL data directory..."

# Try Docker volume first
PG_DATA=""
if docker volume inspect "${CONTAINER_NAME/devops-learning-db-dr/devops-learning-web}_pg_data" &>/dev/null; then
  PG_DATA=$(docker volume inspect "${CONTAINER_NAME/devops-learning-db-dr/devops-learning-web}_pg_data" --format '{{ .Mountpoint }}' 2>/dev/null)
fi

# Fallback: check common paths
if [ -z "$PG_DATA" ] || [ ! -d "$PG_DATA" ]; then
  for path in \
    "/var/snap/docker/common/var-lib-docker/volumes/devops-learning-web_pg_data/_data" \
    "/var/lib/docker/volumes/devops-learning-web_pg_data/_data" \
    "/data/postgres"; do
    if [ -d "$path" ]; then
      PG_DATA="$path"
      break
    fi
  done
fi

if [ -z "$PG_DATA" ] || [ ! -d "$PG_DATA" ]; then
  echo "  ❌ Cannot find PostgreSQL data directory!"
  echo "  Try: docker volume inspect devops-learning-web_pg_data"
  exit 1
fi
echo "  ✅ Found: $PG_DATA"

# ── Step 2: Stop the container ──
echo "2/5 — Stopping PostgreSQL container..."
docker stop "$CONTAINER_NAME" 2>/dev/null || true
sleep 2
echo "  ✅ Container stopped"

# ── Step 3: Backup the corrupted file ──
echo "3/5 — Backing up corrupted postgresql.auto.conf..."
AUTOCONF="$PG_DATA/postgresql.auto.conf"
if [ -f "$AUTOCONF" ]; then
  BACKUP="$AUTOCONF.corrupted.$(date +%Y%m%d%H%M%S)"
  cp "$AUTOCONF" "$BACKUP"
  echo "  ✅ Backup saved: $BACKUP"
  echo "  📋 Corrupted content (first 20 lines):"
  head -20 "$BACKUP" | sed 's/^/     /'
  echo ""
else
  echo "  ⚠️  No existing postgresql.auto.conf found"
fi

# ── Step 4: Write clean postgresql.auto.conf ──
echo "4/5 — Writing clean postgresql.auto.conf (mode: $MODE)..."

if [ "$MODE" = "standby" ]; then
  cat > "$AUTOCONF" <<EOF
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
# Fixed by fix-pg-autoconf.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)

primary_conninfo = 'host=${PRIMARY_HOST} port=5432 user=${REPL_USER} password=${REPL_PASS} application_name=${REPL_SLOT}'
primary_slot_name = '${REPL_SLOT}'
EOF

  # Ensure standby.signal exists
  touch "$PG_DATA/standby.signal"
  chown 999:999 "$PG_DATA/standby.signal"
  echo "  ✅ Configured as STANDBY (replicating from $PRIMARY_HOST)"
else
  cat > "$AUTOCONF" <<EOF
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
# Fixed by fix-pg-autoconf.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

  # Remove standby.signal if it exists (should not be there for primary)
  rm -f "$PG_DATA/standby.signal"
  echo "  ✅ Configured as PRIMARY (standalone)"
fi

# Fix ownership (999 = postgres user inside the container)
chown 999:999 "$AUTOCONF"
chmod 600 "$AUTOCONF"

echo "  📋 New content:"
cat "$AUTOCONF" | sed 's/^/     /'
echo ""

# ── Step 5: Restart the container ──
echo "5/5 — Starting PostgreSQL container..."
docker start "$CONTAINER_NAME"
sleep 5

# Verify it's running
if docker ps --filter "name=$CONTAINER_NAME" --filter "status=running" -q | grep -q .; then
  echo "  ✅ Container running!"
  
  # Wait for PG to be ready
  echo "  ⏳ Waiting for PostgreSQL to accept connections..."
  for i in $(seq 1 15); do
    if docker exec "$CONTAINER_NAME" pg_isready -U devops -d devops_learning 2>/dev/null | grep -q "accepting"; then
      echo "  ✅ PostgreSQL is ready!"
      
      # Show mode
      IS_RECOVERY=$(docker exec "$CONTAINER_NAME" psql -U devops -d devops_learning -t -c "SELECT pg_is_in_recovery();" 2>/dev/null | tr -d ' ')
      if [ "$IS_RECOVERY" = "t" ]; then
        echo "  🟢 Mode: STANDBY (streaming replication)"
      else
        echo "  🟢 Mode: PRIMARY"
      fi
      break
    fi
    echo "    Attempt $i/15..."
    sleep 3
  done
else
  echo "  ❌ Container failed to start! Check logs:"
  echo "     docker logs $CONTAINER_NAME --tail 20"
  exit 1
fi

echo ""
echo "═══════════════════════════════════════════════"
echo "✅ FIX COMPLETE"
echo "═══════════════════════════════════════════════"
echo ""
echo "Verify:"
echo "  docker logs $CONTAINER_NAME --tail 10"
echo "  docker exec $CONTAINER_NAME psql -U devops -d devops_learning -c 'SELECT 1;'"
echo ""
